/*******************************************************************************
 * Copyright 2013 Mojave Innovations GmbH
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * Contributors:
 *     Mojave Innovations GmbH - initial API and implementation
 ******************************************************************************/
package org.entirej.framework.report.enumerations;

public enum EJReportFrameworkMessage
{

    FRAMEWORK_NOT_INITIALISED,

    CANNOT_PERFORM_QUERY_WITH_NO_SERVICE, CANNOT_UPDATE_A_BLOCK_WITH_NO_RECORD,

    NULL_REPORT_CONTROLLER_PASSED_TO_REPORT_PROPS, NULL_QUERY_RECORD_PASSED_TO_METHOD, NULL_TRANSACTION_PASSED_TO_METHOD, NULL_RECORD_PASSED_TO_METHOD, NULL_QUERY_CRITERIA_PASSED_TO_METHOD, NULL_REPORT_PROPERTIES_PASSED_TO_METHOD, NULL_BLOCK_PROPERTIES_PASSED_TO_METHOD, NULL_PROCESSOR_NAME_PASSED_TO_METHOD, NULL_FORM_NAME_PASSED_TO_METHOD, NULL_BLOCK_NAME_PASSED_TO_METHOD, NULL_APPLICATION_MANAGER_PASSED_TO_METHOD, NULL_TRANSLATOR_NAME_PASSED_TO_METHOD, NULL_DATA_REPORT_PASSED_TO_REPORT_CONTROLLER, NULL_PROPERTY_NAMES_PASSED_TO_METHOD, NULL_DATA_TYPE_PASSED_TO_METHOD,

    SETTING_BLOCK_NAME_TO_NULL,

    INVALID_DATA_TYPE_FOR_ITEM, INVALID_ITEM_NAME_PASSED_TO_METHOD, INVALID_ACTION_PROCESSOR_FOR_BLOCK, INVALID_ACTION_PROCESSOR_FOR_REPORT, INVALID_ACTION_PROCESSOR_NAME, INVALID_TRANSACTION_FACTORY_NAME, INVALID_DATA_TYPE_FOR_APP_LEVEL_PARAMETER, INVALID_TRANSLATOR_NAME, INVALID_TRANSACTION_FACTORY, NO_ITEM_ON_FORM, NO_ITEM_ON_BLOCK, NO_BLOCK_ON_FORM, NO_ACTION_PROCESSOR_DEFINED_FOR_REPORT, NO_CONNECTION_FACTORY_DEFINED_FOR_APPLICATION, NO_REPORT_PARAMETER, NO_BLOCK_LEVEL_APP_PROPERTY, NO_FORM_LEVEL_APP_PROPERTY, NO_FORM_PROPERTIES_FOR_REUSABLE_BLOCK, NO_FORM_PROPERTIES_FOR_OBJECTGROUP, NO_FORM_PROPERTIES_FOR_REUSABLE_LOV, NO_OBJECTGROUP_LOCATION_DEFINED, NO_FORM_RENDERER_DEFINED, NO_CURRENT_RECORD_AVAILABLE_PLEASE_CREATE,

    NOT_ITEM_ON_MAIN_SCREEN,

    UNABLE_TO_LOCK_RECORD, UNABLE_TO_FIND_METHOD, UNABLE_TO_FIND_BLOCK, UNABLE_TO_FIND_ITEM_ON_BLOCK, UNABLE_TO_EXECUTE_METHOD, UNABLE_TO_SELECT_CURRENT_RECORD, UNABLE_TO_CALL_METHOD, UNABLE_TO_CREATE_ACTION_PROCESSOR, UNABLE_TO_CREATE_DATA_ACCESS_PROCESSOR, UNABLE_TO_CREATE_TRANSACTION_FACTORY, UNABLE_TO_CREATE_APP_MANAGER, UNABLE_TO_CREATE_APPLICATION_TRANSLATOR, UNABLE_TO_LOAD_FORM_FILE, UNABLE_TO_LOAD_BLOCK_RENDERER, VALUE_CANNOT_BE_CONVERTED_TO_BOOLEAN, VALUE_CANNOT_BE_CONVERTED_TO_INT, VALUE_CANNOT_BE_CONVERTED_TO_FLOAT, VALUE_CANNOT_BE_CONVERTED_TO_DOUBLE, THE_SERVICE_IS_NOT_A_IBLOCKSERVICE, SERVICE_FACTORY_DOES_NOT_CONTAIN_METHOD

}
